---
title: "module-20"
output: html_document
---

```{r}
library(tidyverse)
library(broom)
library(infer)
```

```{r}
f <- "https://raw.githubusercontent.com/difiore/ada-2022-datasets/main/zombies.csv"
z <- read_csv(f, col_names = TRUE)
```

```{r}
z$gender <- factor(z$gender)  # can also use `as.factor()`
z$major <- factor(z$major)  # can also use `as.factor()`
```

```{r}
class(z$gender)
```

```{r}
summary(z$gender)
```

```{r}
plot(z$height ~ z$gender)
```

```{r}
# or, with {ggplot}
ggplot(data = z, aes(x = gender, y = height)) + geom_boxplot()
```

```{r}
m <- lm(data = z, height ~ gender)
summary(m)
```

```{r}
levels(z$gender)
```

```{r}
z$gender <- relevel(z$gender, ref = "Male")
m <- lm(data = z, height ~ gender)
summary(m)
```

```{r}
p <- 1 - pf(q = 276.9, df1 = 1, df2 = 998)
p
```

```{r}
unique(z$major)
```

```{r}
levels(z$major)
```

```{r}
z <- z %>%
    mutate(occupation = case_when(major %in% c("agricultural sciences", "animal husbandry",
        "applied sciences", "biology", "botany", "energy studies", "environmental science",
        "epidemiology", "medicine/nursing", "pharmacology") ~ "natural science",
        major %in% c("business administration", "city planning", "economics", "human services",
            "logistics", "military strategy") ~ "logistics", major %in% c("architecture",
            "integrated water resources management", "mechanical engineering") ~
            "engineering", major %in% c("communication", "criminal justice administration",
            "culinary services", "education", "philosophy", "physical education",
            "psychology") ~ "other"))
z$occupation <- factor(z$occupation)  # can also use `as.factor()`
levels(z$occupation)
```

```{r}
plot(data = z, zombies_killed ~ occupation)
```

```{r}
m <- lm(data = z, zombies_killed ~ occupation)
summary(m)
```

Why is the q = 0.489 instead of 1.403??
```{r}
p <- 1 - pf(q = 0.489, df1 = 3, df2 = 996)  # F test
p
```


One way ANOVA
```{r}
m.aov <- aov(data = z, zombies_killed ~ occupation)
summary(m.aov)
```

```{r}
tidy(m.aov)  # a neater table
```

```{r}
m.lm <- lm(data = z, zombies_killed ~ occupation)
summary(m.lm)
```

```{r}
tidy(m.lm)  # a neater table
```

```{r}
par(mfrow = c(2, 2))
plot(m.lm)  # plot(m.aov) is equivalent
```

Simulation-based inference
```{r}
original.F <- aov(data = z, zombies_killed ~ occupation) %>%
    tidy() %>%
    filter(term == "occupation")
# show aov results for F statistic and p value for omnibus F test
original.F
```

```{r}
permuted.F <- z %>%
    # specify model
specify(zombies_killed ~ occupation) %>%
    # use a null hypothesis of independence
hypothesize(null = "independence") %>%
    # generate permutation replicates
generate(reps = 1000, type = "permute") %>%
    # calculate the F statistic for the aov
calculate(stat = "F")

# plot our F statistic on the distribution of F statistic values generated by
# permutation
visualize(permuted.F) + shade_p_value(obs_stat = original.F$statistic, direction = "greater")
```

```{r}
(p.value <- permuted.F %>%
    get_p_value(obs_stat = original.F$statistic, direction = "greater"))
```

```{r}
original.F$p.value
```

```{r}
p.value
```

```{r}
library(permuco)
m.aovperm <- aovperm(data = z, zombies_killed ~ occupation)
summary(m.aovperm)
```

```{r}
plot(m.aovperm)
```

```{r}
m.lmperm <- lmperm(data = z, zombies_killed ~ occupation)
summary(m.lmperm)
```

```{r}
detach(package:permuco)
```

```{r}
library(coin)
m.aov <- oneway_test(data = z, zombies_killed ~ occupation, distribution = "approximate")
# by default, 10000 replicates are used
m.aov
```


Challenge:
```{r}
f <- "https://raw.githubusercontent.com/difiore/ada-2022-datasets/main/gibbon-femurs.csv"
d <- read_csv(f, col_names = TRUE)
```

```{r}
d$age <- factor(d$age, levels = c("inf", "juv", "subadult", "adult"))
# converts age to a factor and order the age levels so that they are in
# ascending chronological order several ANOVA functions require that
# categorical variables are represented as factors rather than strings
d$sex <- factor(d$sex, levels = c("female", "male"))
# convert sex to a factor
head(d)
```

```{r}
par(mfrow = c(1, 2))
hist(d$femur_length)
qqnorm(d$femur_length)
```

```{r}
plot(data = d, femur_length ~ age)  # boxplot with medians

# calculate average and SD by group
stats <- d %>%
    group_by(age) %>%
    summarize(`mean(femur_length)` = mean(femur_length), `sd(femur_length)` = sd(femur_length))

# add means to plot
points(1:4, stats$`mean(femur_length)`, pch = 4, cex = 1.5)
```

```{r}
# check that variances are roughly equal (ratio of max/min is <2)
max(stats$`sd(femur_length)`)/min(stats$`sd(femur_length)`)
```

```{r}
# subtract relevant group mean from each data point
means.centered <- d$femur_length - stats[as.numeric(d$age), 2]

# graphical test for normality of group-centered means
qqnorm(means.centered$`mean(femur_length)`)  # looks good!
```

```{r}
# now do graphical test within each group
par(mfrow = c(1, 2))
hist(d$femur_length[d$age == "inf"], main = "Infant", xlab = "Femur Length (cm)")
qqnorm(d$femur_length[d$age == "inf"])
```

```{r}
hist(d$femur_length[d$age == "juv"], main = "Juvenile", xlab = "Femur Length (cm)")
qqnorm(d$femur_length[d$age == "juv"])
```

```{r}
hist(d$femur_length[d$age == "subadult"], main = "Subadult", xlab = "Femur Length (cm)")
qqnorm(d$femur_length[d$age == "subadult"])
```

```{r}
hist(d$femur_length[d$age == "adult"], main = "Adult", xlab = "Femur Length (cm)")
qqnorm(d$femur_length[d$age == "adult"])
```

```{r}
par(mfrow = c(1, 1))
plot(data = d, femur_length ~ age, xlab = "Age", ylab = "Femur Length (cm)")
```

```{r}
m <- aov(data = d, femur_length ~ age)  # femur length related to age
summary(m)
```

```{r}
m <- lm(data = d, femur_length ~ age)
summary(m)
```


Post-hoc test in ANOVA
```{r}
pairwise.t.test(d$femur_length, d$age, p.adj = "bonferroni")
```

```{r}
m <- aov(d$femur_length ~ d$age)
posthoc <- TukeyHSD(m, which = "d$age", conf.level = 0.95)
posthoc  # all age-sex classes differ
```

```{r}
(m <- kruskal.test(data = d, femur_length ~ age))
```

```{r}
# to show that this is the same as the test using ranks...  use {dplyr} to sort
# by femur.length...
d <- arrange(d, femur_length)
# then use {dplyr} to add new variable of rank femur_length
d <- mutate(d, femur_rank = row(data.frame(d$femur_length)))
(m <- kruskal.test(data = d, femur_rank ~ age))
```

```{r}
# pairwise Mann-Whitney U test the arguments are a vector of data, a vector
# with the grouping factor, and the multiple test correction method...
pairwise.wilcox.test(d$femur_length, d$age, p.adjust.method = "bonferroni")
```

```{r}
# `dunn.test()` and `conover.test()` include another argument, `kw=` which is
# whether or not to output KW results
library(dunn.test)
dunn.test(d$femur_length, g = d$age, method = "bonferroni", kw = TRUE)
```

```{r}
detach(package:dunn.test)
library(conover.test)
conover.test(d$femur_length, g = d$age, method = "bonferroni", kw = TRUE)
```


Multiple factor ANOVA
```{r}
stats <- d %>% group_by(age, sex) %>%
  summarize("mean(femur_length)" = mean(femur_length),
    "sd(femur_length)"= sd(femur_length))
```

```{r}
# first we calculate averages by combination of factors
max(stats$`sd(femur_length)`)/min(stats$`sd(femur_length)`)
```

```{r}
# check that variances in each group are roughly equal (ratio of max/min is <2)
p <- ggplot(data=d, aes(y = femur_length, x = sex)) + geom_boxplot() +
  facet_wrap(~age, ncol=4) +
  xlab("Sex") + ylab("Femur Length (cm)")
# and let's plot what the data look like
# p <- p + geom_point() # uncommenting this shows all points
p <- p + stat_summary(data=d, aes(y = femur_length, x = sex),
  fun = base::mean,
  # make sure we use {base} version of mean
  color = "darkgreen", geom = "point", shape = 8, size = 6)
p
```

```{r}
summary(aov(data = d, femur_length ~ age))
```

```{r}
summary(aov(data = d, femur_length ~ sex))
```

```{r}
m <- summary(aov(data = d, femur_length ~ age + sex))
m
```

```{r}
m <- aov(data = d, femur_length ~ age + sex + age:sex)
# the colon (:) operator includes specific interaction terms
summary(m)
```

```{r}
m <- aov(data = d, femur_length ~ age * sex)
# asterisk (*) operator includes all interaction terms
summary(m)
```

```{r}
m <- lm(data = d, femur_length ~ age * sex)
# or using the lm() function...
summary(m)
```

```{r}
interaction.plot(
  x.factor = d$age,
  xlab = "Age",
  trace.factor = d$sex,
  trace.label = "Sex",
  response = d$femur_length,
  fun = base::mean, # make sure we use {base} version
  ylab = "Mean Femur Length"
)
```

```{r}
library(permuco)
m.aovperm <- aovperm(data = d, femur_length ~ age + sex + age:sex)
summary(m.aovperm)
```

```{r}
detach(package:permuco)
```


Type 1, II, and III ANOVA
```{r}
m1 <- aov(data = d, femur_length ~ age + sex)
summary(m1)
```

```{r}
m2 <- aov(data = d, femur_length ~ sex + age)
summary(m2)
```

```{r}
m1 <- lm(data = d, femur_length ~ age + sex)
summary(m1)
```

```{r}
m2 <- lm(data = d, femur_length ~ sex + age)
summary(m2)
```

```{r}
table(d$sex, d$age)
```

```{r}
library(car)
```

```{r}
m1 <- aov(data = d, femur_length ~ age + sex)
m1 <- Anova(m1, type = "II")
m1
```

```{r}
m2 <- aov(data = d, femur_length ~ sex + age)
m2 <- Anova(m2, type = "II")
m2
```

```{r}
m1 <- aov(data = d, femur_length ~ age * sex)
m1 <- Anova(m1, type = "III")
m1
```

```{r}
m2 <- aov(data = d, femur_length ~ sex * age)
m2 <- Anova(m2, type = "III")
m2
```

```{r}
detach(package:car)
```

```{r}
par(mfrow = c(1, 1))
curve(dchisq(x, df = 1), col = "green", lty = 3, lwd = 2, xlim = c(0, 20), main = "Some Example Chi-Square Distributions",
    sub = "(vertical line shows critical value for df=3)", ylab = "f(x)", xlab = "x")
curve(dchisq(x, df = 3), col = "blue", lty = 3, lwd = 2, add = TRUE)
curve(dchisq(x, df = 5), col = "red", lty = 3, lwd = 2, add = TRUE)
curve(dchisq(x, df = 10), col = "purple", lty = 3, lwd = 2, add = TRUE)
legend("right", c("df=1", "df=3", "df=5", "df=10"), lty = c(3, 3, 3, 3), lwd = 2,
    col = c("green", "blue", "red", "purple", "black"), bty = "n", cex = 0.75)

crit <- qchisq(p = 0.95, df = 3)
crit

abline(v = crit)
abline(h = 0)
polygon(cbind(c(crit, seq(from = crit, to = 20, length.out = 1000), 8), c(0, dchisq(seq(from = crit,
    to = 20, length.out = 1000), df = 3), 0)), border = "black", col = rgb(0, 0,
    1, 0.5))
```


Challenge:
```{r}
(obs.table <- table(z$occupation))
```

```{r}
# returns the same as summary()
(exp.table <- rep(0.25 * length(z$occupation), 4))
```

```{r}
# equal expectation for each of 4 categories
occupation.matrix <- data.frame(cbind(obs.table, exp.table, (obs.table - exp.table)^2/exp.table))
names(occupation.matrix) <- c("Oi", "Ei", "(Oi-Ei)^2/Ei")
occupation.matrix
```

```{r}
(X2 <- sum(occupation.matrix[, 3]))
```

```{r}
(p <- 1 - pchisq(q = X2, length(obs.table) - 1))
```

```{r}
chisq.test(x = obs.table, p = c(0.25, 0.25, 0.25, 0.25))
```

```{r}
# here p is a vector of expected proportions... default is uniform
chisq.test(x = obs.table)
```

```{r}
chisq.test(x = obs.table, p = c(0.42, 0.07, 0.22, 0.29))
```

```{r}
(obs.table = table(z$gender, z$occupation))
```

```{r}
mosaicplot(t(obs.table), main = "Contingency Table", col = c("darkseagreen", "gray"))
```

```{r}
(r <- rowSums(obs.table))  # row margins
```

```{r}
(c <- colSums(obs.table))  # column margins
```

```{r}
(nr <- nrow(obs.table))  # row dimensions
```

```{r}
(nc <- ncol(obs.table))  # column dimensions
```

```{r}
(exp.table <- matrix(rep(c, each = nr) * r/sum(obs.table), nrow = nr, ncol = nc,
    dimnames = dimnames(obs.table), byrow = FALSE))
```

```{r}
# calculates the product of c*r and divides by total
(X2 <- sum((obs.table - exp.table)^2/exp.table))
```

```{r}
(p <- 1 - pchisq(q = X2, df = (nr - 1) * (nc - 1)))
```

```{r}
chisq.test(x = obs.table)
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```